---
title: "R Notebook"
output: html_notebook
---

```{r}
#Loading pre-installed libraries
suppressMessages(suppressWarnings(library(tidyverse)))
suppressMessages(suppressWarnings(library(gganimate)))
suppressMessages(suppressWarnings(library(cowplot)))
suppressMessages(suppressWarnings(library(repr)))
suppressMessages(suppressWarnings(library(gifski)))


#turning off warnings
options(warn=-1)

#setting plot width and height
options(repr.plot.width=15, repr.plot.height = 10)
```

```{r}
#reading in non-tracking data

#includes schedule info for games
df_games <- read_csv("games.csv",
                    col_types = cols())

#includes play-by-play info on specific plays
df_plays <- read_csv("plays.csv",
                    col_types = cols())

#includes background info for players
df_pffScouting <- read_csv("pffScoutingData.csv",
                      col_types = cols())

```


```{r}
#Reading tracking data (needs to be done iteratively)

#weeks of NFL season
weeks <- seq(1) # CURRENTLY ONLY READS IN WEEK 1

#blank dataframe to store tracking data
df_tracking <- data.frame()

#iterating through all weeks
for(w in weeks){
    
    #temporary dataframe used for reading week for given iteration
    df_tracking_temp <- read_csv(paste0("week",w,".csv"),
                                col_types = cols())
    
    #storing temporary dataframe in full season dataframe
    df_tracking <- bind_rows(df_tracking_temp, df_tracking)                            
    
}
```


```{r}
# standardization of direction
df_tracking <- df_tracking %>%
                mutate(x = ifelse(playDirection == "left", 120-x, x),
                       y = ifelse(playDirection == "left", 160/3 - y, y))
```

```{r}
the_game = 2021090900 #SELECTS THE GAME AND PLAY
the_play = 97

example_play <- df_plays %>%
                select(gameId, playId, playDescription) %>% 
                filter(gameId == the_game, playId == the_play) 

#merging games data to play
example_play <- inner_join(example_play, df_games, 
                           by = c("gameId" = "gameId"))

#merging tracking data to play
example_play <- inner_join(example_play, df_tracking,
                           by = c("gameId" = "gameId", "playId" = "playId"))

example_play <- left_join(example_play, 
                          df_pffScouting %>% select(pff_role, gameId, playId,nflId),
                          by = c("gameId" = "gameId", "playId" = "playId", "nflId" = "nflId")) 
                          #%>% filter(!pff_role %in% c("Coverage", "Pass Route")) 

example_play <- example_play %>% filter(frameId == 1)

example_play <- full_join(example_play, 
                          test_off %>% select(frameId, normforce, gameId, playId,nflId), 
                          by = c("gameId" = "gameId", "playId" = "playId",
                                "nflId" = "nflId", "frameId" = "frameId"))

example_play <- example_play %>% filter(!pff_role %in% c("Coverage", "Pass Route", "Pass Rush")) 
```



```{r}
# Create the tracking data display ----------------------------------------

# Use the Lopez code:
# General field boundaries
xmin <- 0
xmax <- 160/3
hash_right <- 38.35
hash_left <- 12
hash_width <- 3.3

# Specific boundaries for a given play
ymin <- 0
ymax <- 120
df_hash <- expand.grid(x = c(0, 23.36667, 29.96667, xmax), y = (10:110))
df_hash <- df_hash %>% filter(!(floor(y %% 5) == 0))
df_hash <- df_hash %>% filter(y < ymax, y > ymin)
line_of_scrimmage <- df_plays %>% filter(gameId == the_game, playId == the_play) %>% select(yardlineNumber)
line_of_scrimmage <- line_of_scrimmage$yardlineNumber + 10

plot_title <- str_trim(gsub("\\s*\\([^\\)]+\\)","",as.character(example_play$playDescription[1])))

```

```{r}

# creating the plot:
at_catch_plot <- ggplot() +
  #green base field
  annotate("rect", xmin = 0, xmax = 120, ymin = 0, ymax = 160/3, alpha = 0.4,
           color = "gray", fill = "darkgreen") +
  #hash marks
  annotate("text", y = df_hash$x[df_hash$x < 55/2], alpha = 0.75, color = "white",
           x = df_hash$y[df_hash$x < 55/2], label = "|", vjust = -0.3, hjust = 0.4) +
  annotate("text", y = df_hash$x[df_hash$x > 55/2], alpha = 0.75, color = "white",
           x = df_hash$y[df_hash$x > 55/2], label = "|", vjust = 1, hjust = 0.4) +
  #yard lines
  annotate("segment", y = xmin,
           x = seq(max(10, ymin), min(ymax, 110), by = 5),
           yend =  xmax, color = "white",
           xend = seq(max(10, ymin), min(ymax, 110), by = 5), alpha = 0.75) +
  #yard numbers
  annotate("text", y = rep(hash_left, 11), x = seq(10, 110, by = 10), alpha = 0.75,
           label = c("   G", seq(10, 50, by = 10), rev(seq(10, 40, by = 10)), "G   "),
           angle = 0, size = 4, color = "white") +
  annotate("text", y = rep((xmax - hash_left), 11), x = seq(10, 110, by = 10),
           label = c("G   ", seq(10, 50, by = 10), rev(seq(10, 40, by = 10)), "   G"),
           angle = 180, size = 4, alpha = 0.75, color = "white") +
  #bounds
  annotate("segment", y = c(xmin, xmin, xmax, xmax),
           x = c(ymin, ymax, ymax, ymin),
           yend = c(xmin, xmax, xmax, xmin),
           xend = c(ymax, ymax, ymin, ymin), colour = "white", alpha = 0.25) +
  annotate("segment", y = xmin, yend = xmax,
           x = line_of_scrimmage,
           xend = line_of_scrimmage,
           color = "gold", size = 2) +
  
  #adding players
  geom_point(data = example_play,
             aes(x = x, y = y, shape = team, fill = team, group = nflId, 
                 size = team, color = team), 
             alpha = 0.7) + 
  # addingt force vectors
   #geom_segment(data = example_play,
    #           aes(y = y, x = x, xend = x + normforce, yend = y,
     #              group = nflId, alpha = player_role),
      #         color = "black",
       #        alpha = 0.75,
        #       size = 1,
         #      arrow = arrow(length = unit(0.01, "npc"))) +
  
  scale_size_manual(values = c(5, 4, 5), guide = "none") + 
  scale_shape_manual(values = c(21, 16, 21), guide = "none") +
  scale_fill_manual(values = c("blue", "#663300", "red"), guide = "none") + 
  scale_colour_manual(values = c("black", "#663300", "black"), guide = "none") +
  
  ylim(xmin, xmax) + 
  coord_fixed() + 

#titling plot with play description
  labs(title = plot_title) +
  
#applying theme
  theme_nothing() + 
  theme(plot.title = element_text()) #+

#setting animation parameters
#transition_time(frameId)  +
#ease_aes('linear')

at_catch_plot
```
