```{r}
suppressMessages(suppressWarnings(library(tidyverse)))
suppressMessages(suppressWarnings(library(gganimate)))
suppressMessages(suppressWarnings(library(cowplot)))
suppressMessages(suppressWarnings(library(repr)))
suppressMessages(suppressWarnings(library(gifski)))

# turning off warnings
options(warn=-1)

# setting plot width and height
options(repr.plot.width=15, repr.plot.height = 10)
```

```{r}
# reading in data

# game
df_games <- read_csv("Data/games.csv",
                    col_types = cols())

#play
df_plays <- read_csv("Data/plays.csv",
                    col_types = cols())

# pff
df_pffScouting <- read_csv("Data/pffScoutingData.csv",
                      col_types = cols())

# force
df_merged <- suppressMessages(read_csv("Data/forces_week1.csv",
                    col_types = cols()))

# dropping index column
df_merged <- df_merged[-c(1)]

# selecting only linemen
df_merged <- df_merged %>% filter(pff_role %in% c("Pass Block", "Pass Rush"))

# tracking
df_tracking <- read_csv("Data/week1_cut_by_frame_clean.csv",
                    col_types = cols())
```

```{r}
#filtering and processing of data

# finding only pass block, pass rush, and pass
df_positions <- df_pffScouting %>% select(c(nflId, pff_role)) %>% distinct(nflId, .keep_all = TRUE) %>% filter(pff_role %in% c("Pass Block", "Pass Rush", "Pass"))

# getting only the forces
df_interest_x <- df_merged %>% select(c(nflId, gameId, playId, frameId, x_force)) %>% na.omit

df_interest_x$x_force <- abs(df_interest_x$x_force)

df_interest_x <- df_interest_x %>%
  select(c(gameId, playId, nflId, frameId, x_force)) %>%
  group_by(gameId, playId) %>%
  mutate(maxnum = max(x_force), minnum = min(x_force)) %>%
  mutate(norm_x_force = ((x_force - minnum)/(maxnum - minnum))*10)

df_interest_x <- df_interest_x %>% select(-c(maxnum, minnum, x_force))
```

```{r}
# filter tracking so that it only has the right players
df_data <- df_tracking %>% left_join(df_positions, by = c("nflId" = "nflId")) %>% filter(team == "football" | pff_role == "Pass" |pff_role == "Pass Rush" | pff_role == "Pass Block")

# combine with force data
df_data <- df_data %>% left_join(df_interest_x, by = c( "nflId" = "nflId", "gameId" = "gameId", "playId" = "playId", "frameId" = "frameId"))

```


```{r}
the_game = 2021090900 #SELECTS THE GAME AND PLAY
the_play = 97

# selects gameId, playId, and description
example_play <- df_plays %>%
                select(gameId, playId, playDescription) %>% 
                filter(gameId == the_game, playId == the_play) 

#selects game details
example_play <- inner_join(example_play, df_games,
                           by = c("gameId" = "gameId"))

#merging tracking data to play
example_play <- inner_join(example_play, df_data,
                           by = c("gameId" = "gameId", "playId" = "playId"))

example_play <- example_play %>% filter(pff_role == "Pass" | pff_role == "Pass Block")

```



```{r}
# animation

# use the Lopez code:
# field boundaries
xmin <- 0
xmax <- 160/3
hash_right <- 38.35
hash_left <- 12
hash_width <- 3.3


# boundaries for a given play
ymin <- 0
ymax <- 120
df_hash <- expand.grid(x = c(0, 23.36667, 29.96667, xmax), y = (10:110))
df_hash <- df_hash %>% filter(!(floor(y %% 5) == 0))
df_hash <- df_hash %>% filter(y < ymax, y > ymin)
line_of_scrimmage <- df_plays %>% filter(gameId == the_game, playId == the_play) %>% select(yardlineNumber)
line_of_scrimmage <- line_of_scrimmage$yardlineNumber + 10

plot_title <- str_trim(gsub("\\s*\\([^\\)]+\\)","",as.character(example_play$playDescription[1])))

```

```{r}
# creating the plot:
at_catch_plot <- ggplot() +
  #green base field
  annotate("rect", xmin = 20, xmax = 60, ymin = 0, ymax = 160/3, alpha = 0.4,
           color = "gray", fill = "darkgreen") +
  #hash marks
  annotate("text", y = df_hash$x[df_hash$x < 55/2], alpha = 0.75, color = "white",
           x = df_hash$y[df_hash$x < 55/2], label = "|", vjust = -0.3, hjust = 0.4) +
  annotate("text", y = df_hash$x[df_hash$x > 55/2], alpha = 0.75, color = "white",
           x = df_hash$y[df_hash$x > 55/2], label = "|", vjust = 1, hjust = 0.4) +
  #yard lines
  annotate("segment", y = xmin,
           x = seq(max(10, ymin), min(ymax, 110), by = 5),
           yend =  xmax, color = "white",
           xend = seq(max(10, ymin), min(ymax, 110), by = 5), alpha = 0.75) +
  #yard numbers
  annotate("text", y = rep(hash_left, 11), x = seq(10, 110, by = 10), alpha = 0.75,
           label = c("   G", seq(10, 50, by = 10), rev(seq(10, 40, by = 10)), "G   "),
           angle = 0, size = 4, color = "white") +
  annotate("text", y = rep((xmax - hash_left), 11), x = seq(10, 110, by = 10),
           label = c("G   ", seq(10, 50, by = 10), rev(seq(10, 40, by = 10)), "   G"),
           angle = 180, size = 4, alpha = 0.75, color = "white") +
  #bounds
  annotate("segment", y = c(xmin, xmin, xmax, xmax),
           x = c(ymin, ymax, ymax, ymin),
           yend = c(xmin, xmax, xmax, xmin),
           xend = c(ymax, ymax, ymin, ymin), colour = "white", alpha = 0.25) +
  annotate("segment", y = xmin, yend = xmax,
           x = line_of_scrimmage,
           xend = line_of_scrimmage,
           color = "gold", size = 2) +
  
  #adding players
  geom_point(data = example_play,
             aes(x = x, y = y, shape = team, fill = team, group = nflId, 
                 size = team, color = team), alpha = .8) + 
  geom_segment(data = example_play, aes(x = x, y = y, xend = x + norm_x_force, yend = y),
                colour = c("black"), arrow = arrow(length = unit(0.01, "npc"))) +
  scale_size_manual(values = c(4, 4, 4), guide = "none") + 
  scale_shape_manual(values = c(21, 16, 21), guide = "none") +
  scale_fill_manual(values = c("red", "#663300", "red"), guide = "none") + 
  scale_colour_manual(values = c("black", "#663300", "black"), guide = "none") +
  
  ylim(xmin, xmax) + 
coord_fixed() + 

#titling plot with play description
# labs(title = plot_title) +
  
#applying theme
theme_nothing() + 
theme(plot.title = element_text(), plot.margin=grid::unit(c(0,0,0,0), "mm")) +

#setting animation parameters
transition_time(frameId)  +
ease_aes('linear')

suppressWarnings(at_catch_plot)
```
