```{r}
suppressMessages(suppressWarnings(library(tidyverse)))
suppressMessages(suppressWarnings(library(gganimate)))
suppressMessages(suppressWarnings(library(cowplot)))
suppressMessages(suppressWarnings(library(repr)))
suppressMessages(suppressWarnings(library(gifski)))

# turning off warnings
options(warn=-1)
```

```{r}
# reading in data

# game
df_games <- read_csv("games.csv",
                    col_types = cols())

#play
df_plays <- read_csv("plays.csv",
                    col_types = cols())

#player
df_players <- read_csv("players.csv",
                    col_types = cols())

# pff
df_pffScouting <- read_csv("pffScoutingData.csv",
                      col_types = cols())

# force
df_force <- read_csv("forces_week5.csv",
                    col_types = cols())

# selecting force for only linemen
df_force <- df_force %>% filter(pff_role %in% c("Pass Block", "Pass Rush"))

# tracking
df_tracking <- read_csv("week5_cut_by_frame_clean.csv",
                    col_types = cols())
```

```{r}
#filtering and processing of data

# sample game and play
the_game = 2021100700
the_play = 2051

# filtering for the sample game and play
df_data <- df_tracking %>% filter(gameId == the_game, playId == the_play)
df_linemen <- df_pffScouting %>% filter(gameId == the_game, playId == the_play)

# getting only the forces
df_interest_x <- df_force %>% filter(gameId == the_game, playId == the_play)
df_interest_x <- df_interest_x  %>% select(c(nflId, gameId, playId, 
                                             frameId, x_force)) %>% na.omit

# normalizing the force
df_interest_x <- df_interest_x %>%
  select(c(gameId, playId, nflId, frameId, x_force)) %>%
  group_by(gameId, playId) %>%
  mutate(maxnum = max(x_force), minnum = min(x_force)) %>%
  mutate(norm_x_force = ((x_force - minnum)/(maxnum - minnum))*10)

df_interest_x <- df_interest_x %>% select(-c(maxnum, minnum, x_force))

# combining tracking and position dataframes
df_data <- df_data %>% left_join(df_linemen, by = c("nflId" = "nflId")) %>% 
  filter(team == "football" | pff_role == "Pass" |
         pff_role == "Pass Rush" | pff_role == "Pass Block")

# combine with force data
df_data <- df_data %>% left_join(df_interest_x, by = c( "nflId" = "nflId", 
                                                        "frameId" = "frameId"))

# selects gameId, playId, and description
example_play <- df_plays %>%
                select(gameId, playId, playDescription) %>% 
                filter(gameId == the_game, playId == the_play) 

#selects game details
example_play <- inner_join(example_play, df_games,
                           by = c("gameId" = "gameId"))

example_play <- df_data

# offensive force
offense_example_play <- example_play %>% 
                        filter(pff_role == "Pass Block")

# defensive force
defense_example_play <- example_play %>% 
                        filter(pff_role == "Pass Rush")

```

```{r}
# animation bounds

# use the Lopez code:
# field boundaries
xmin <- 0
xmax <- 160/3
hash_right <- 38.35
hash_left <- 12
hash_width <- 3.3


# boundaries for a given play
ymin <- 0
ymax <- 120
df_hash <- expand.grid(x = c(0, 23.36667, 29.96667, xmax), y = (10:110))
df_hash <- df_hash %>% filter(!(floor(y %% 5) == 0))
df_hash <- df_hash %>% filter(y < ymax, y > ymin)
line_of_scrimmage <- df_plays %>% filter(gameId == the_game, playId == the_play) %>% select(yardlineNumber)
line_of_scrimmage <- line_of_scrimmage$yardlineNumber + 10

```

```{r}
# creating the plot:
offense_plot <- ggplot() +
  
  #green base field
  annotate("rect", xmin = 40, xmax = 80, ymin = 0, ymax = 160/3, alpha = 0.4,
           color = "gray", fill = "darkgreen") +
  
  #hash marks
  annotate("text", y = df_hash$x[df_hash$x < 55/2], size = 8, alpha = 0.75, color = "white",
           x = df_hash$y[df_hash$x < 55/2], label = "|", vjust = -0.3, hjust = 0.4) +
  annotate("text", y = df_hash$x[df_hash$x > 55/2], size = 8, alpha = 0.75, color = "white",
           x = df_hash$y[df_hash$x > 55/2], label = "|", vjust = 1, hjust = 0.4) +
  
  #yard lines
  annotate("segment", y = xmin,
           x = seq(max(10, ymin), min(ymax, 110), by = 5),
           yend =  xmax, color = "white",
           xend = seq(max(10, ymin), min(ymax, 110), by = 5), size = .75, alpha = 0.75) +
  
  #yard numbers
  annotate("text", y = rep(hash_left, 11), x = seq(10, 110, by = 10), alpha = 0.75,
           label = c("   G", seq(10, 50, by = 10), rev(seq(10, 40, by = 10)), "G   "),
           angle = 0, size = 8, color = "white") +
  annotate("text", y = rep((xmax - hash_left), 11), x = seq(10, 110, by = 10),
           label = c("G   ", seq(10, 50, by = 10), rev(seq(10, 40, by = 10)), "   G"),
           angle = 180, size = 8, alpha = 0.75, color = "white") +
  
  # bounds
  annotate("segment", y = c(xmin, xmin, xmax, xmax),
           x = c(ymin, ymax, ymax, ymin),
           yend = c(xmin, xmax, xmax, xmin),
           xend = c(ymax, ymax, ymin, ymin), colour = "white", alpha = 0.25) +
  
  # line of scrimmage
  annotate("segment", y = xmin, yend = xmax,
           x = line_of_scrimmage,
           xend = line_of_scrimmage,
           color = "gold", size = 2.5) +
  
  #adding players
  geom_point(data = example_play,
             aes(x = x, y = y, shape = team, fill = team, group = nflId, 
                 size = team, color = team), alpha = .8) +  
  # force vectors
  geom_segment(data = offense_example_play, 
               aes(x = x, y = y, xend = x - norm_x_force, yend = y),
               colour = c("black"), arrow = arrow(length = unit(0.01, "npc"))) +
  scale_size_manual(values = c(8, 8, 8), guide = "none") + 
  scale_shape_manual(values = c("football" = 16, "SEA" = 21, "LA" = 21), guide = "none") +
  scale_fill_manual(values = c("football" = "#663300", "SEA" = "#69BE28", "LA" = "#003594"), 
                    guide = "none") + 
  scale_colour_manual(values = c("football" = "#663300", "SEA" = "black", "LA" = "black"), 
                      guide = "none") +
  ylim(xmin, xmax) + 
  coord_fixed() + 

  #applying theme
  theme_nothing() + 
  theme(plot.title = element_text(), plot.margin=grid::unit(c(0,0,0,0), "mm")) +
  
  #setting animation parameters
  transition_time(frameId)  +
  ease_aes('linear')

suppressWarnings(animate(offense_plot, height = 1440, width = 1440))
```


```{r}
# creating the plot:
defense_plot <- ggplot() +
  #green base field
  annotate("rect", xmin = 40, xmax = 80, ymin = 0, ymax = 160/3, alpha = 0.4,
           color = "gray", fill = "darkgreen") +
  
  #hash marks
  annotate("text", y = df_hash$x[df_hash$x < 55/2], size = 8, alpha = 0.75, color = "white",
           x = df_hash$y[df_hash$x < 55/2], label = "|", vjust = -0.3, hjust = 0.4) +
  annotate("text", y = df_hash$x[df_hash$x > 55/2], size = 8, alpha = 0.75, color = "white",
           x = df_hash$y[df_hash$x > 55/2], label = "|", vjust = 1, hjust = 0.4) +
  
  #yard lines
  annotate("segment", y = xmin,
           x = seq(max(10, ymin), min(ymax, 110), by = 5),
           yend =  xmax, color = "white",
           xend = seq(max(10, ymin), min(ymax, 110), by = 5), size = .75, alpha = 0.75) +
  
  #yard numbers
  annotate("text", y = rep(hash_left, 11), x = seq(10, 110, by = 10), alpha = 0.75,
           label = c("   G", seq(10, 50, by = 10), rev(seq(10, 40, by = 10)), "G   "),
           angle = 0, size = 8, color = "white") +
  annotate("text", y = rep((xmax - hash_left), 11), x = seq(10, 110, by = 10),
           label = c("G   ", seq(10, 50, by = 10), rev(seq(10, 40, by = 10)), "   G"),
           angle = 180, size = 8, alpha = 0.75, color = "white") +
  
  # bounds
  annotate("segment", y = c(xmin, xmin, xmax, xmax),
           x = c(ymin, ymax, ymax, ymin),
           yend = c(xmin, xmax, xmax, xmin),
           xend = c(ymax, ymax, ymin, ymin), colour = "white", alpha = 0.25) +
  
  # line of scrimmage
  annotate("segment", y = xmin, yend = xmax,
           x = line_of_scrimmage,
           xend = line_of_scrimmage,
           color = "gold", size = 2.5) +
  
  #adding players
  geom_point(data = example_play,
             aes(x = x, y = y, shape = team, fill = team, group = nflId, 
                 size = team, color = team), alpha = .8) + 
  # force vectors
  geom_segment(data = defense_example_play, 
               aes(x = x, y = y, xend = x - norm_x_force, yend = y),
               colour = c("black"), arrow = arrow(length = unit(0.01, "npc"))) +
  scale_size_manual(values = c(8, 8, 8), guide = "none") + 
  scale_shape_manual(values = c("football" = 16, "SEA" = 21, "LA" = 21), guide = "none") +
  scale_fill_manual(values = c("football" = "#663300", "SEA" = "#69BE28", "LA" = "#003594"), 
                    guide = "none") + 
  scale_colour_manual(values = c("football" = "#663300", "SEA" = "black", "LA" = "black"), 
                      guide = "none") +
  ylim(xmin, xmax) + 
  coord_fixed() + 

  #applying theme
  theme_nothing() + 
  theme(plot.title = element_text(), plot.margin=grid::unit(c(0,0,0,0), "mm")) +
  
  #setting animation parameters
  transition_time(frameId)  +
  ease_aes('linear')

suppressWarnings(animate(defense_plot, height = 1440, width = 1440))
````

