---
title: "R Notebook"
output: html_notebook
---
```{r}
suppressMessages(suppressWarnings(library(tidyverse)))
```

```{r}
df_pffScouting <- read_csv("pffScoutingData.csv",
                      col_types = cols())

#Reading tracking data (needs to be done iteratively)

#weeks of NFL season
weeks <- seq(1) # CURRENTLY ONLY READS IN WEEK 1

#blank dataframe to store tracking data
df_tracking <- data.frame()

#iterating through all weeks
for(w in weeks){
    
    #temperory dataframe used for reading week for given iteration
    df_tracking_temp <- read_csv(paste0("week",w,".csv"),
                                col_types = cols())
    
    #storing temporary dataframe in full season dataframe
    df_tracking <- bind_rows(df_tracking_temp, df_tracking)                            
    
}

```


```{r}
#play_passers <- df_pffScouting %>% filter(pff_role == "Pass") %>%
 # dplyr::select(gameId, playId, nflId) %>% mutate(is_passer = 1)


#passer_tracking_data <- df_tracking %>%
  #left_join(play_passers, by = c("gameId", "playId", "nflId")) %>%
  #filter(!is.na(is_passer))


passer_tracking_data <- df_tracking %>%
  mutate(is_start = as.numeric(event %in% c("autoevent_ballsnap", "ball_snap")),
         # Now all of the options for the end of the ball carrier sequence:
         is_end = as.numeric(event %in% c("fumble", "handoff", "lateral",
                                          "autoevent_passforward", "pass_forward",
                                          "qb_sack", "qb_strip_sack", "run")))

frame_seq_info <- passer_tracking_data %>% group_by(gameId, playId) %>%
  mutate(any_start = any(is_start == 1), any_end = any(is_end == 1)) %>%
  filter(any_start, any_end) %>%
  summarize(start_frame = frameId[which(is_start == 1)[1]],
            end_frame = frameId[which(is_end == 1 & frameId > start_frame)[1]], 
            .groups = "drop")
```

```{r}
passer_tracking_seq_data <- passer_tracking_data %>%
  left_join(frame_seq_info, by = c("gameId", "playId")) %>%
  filter(!is.na(start_frame), !is.na(end_frame),
         frameId >= start_frame, frameId <= end_frame)
# Naming the frame
passer_tracking_seq_data <- passer_tracking_seq_data %>%
  mutate(new_frameId = frameId - start_frame + 1)

week1_cut_by_frame_clean <- passer_tracking_seq_data %>% select(-c("is_start", "is_end", "start_frame", "end_frame", "frameId"))

colnames(week1_cut_by_frame_clean)[colnames(week1_cut_by_frame_clean) == "new_frameId"] = "frameId"
```


```{r}
write.csv(passer_tracking_seq_data,"week1_cut_by_frame.csv", row.names = FALSE)
write.csv(week1_cut_by_frame_clean,"week1_cut_by_frame_clean.csv", row.names = FALSE)
```

